services:
  sonarr:
    ports:
      - "8989:8989"
  radarr:
    ports:
      - "7878:7878"
  lidarr:
    ports:
      - "8686:8686"
  bazarr:
    ports:
      - "6767:6767"
  prowlarr:
    ports:
      - "9696:9696"
  qbittorrent:
    ports:
      - "8080:8080"
  